services:
  storefrontapp:
    build:
      context: .
#    command: bash start-dev.sh   -> command already present in Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
      - "5006:5006"
    volumes:
      - .:/storefront:z
    networks:
      - ecommerce-net
networks:
  ecommerce-net:
    name: ecommerce-net
    external: true
volumes:
  db: